### ISSUE TITLE
Issuw while installing the package

### ISSUE THREAD

**Issue by priyadarshiniMuthuraman** [hedgedoc/html-to-react#28]
My react version is 17.0.2 but I am unable to install the react-html-parser, getting the error has below. Kindly guide on this.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/43378213/147267857-1d9b673f-3c8c-4259-ab90-05f1fdd4d177.png">

**Comment by mrdrogdrog** [comment]
Hi, `react-html-parser` is the npm package of the original version of this lib that is hosted here: https://github.com/peternewnham/react-html-parser .

This package is a hard fork which we created because we use it in your project. You can install ist with `@hedgedoc/html-to-react`. Sorry for the wrong package name in the README and on npm :sweat_smile: . I updated the descriptions.

**Comment by priyadarshiniMuthuraman** [comment]
@mrdrogdrog Thank you your swift update It worked. You need to change the usage part in Readme file

Usage
import React from 'react';
import convertHtmlToReact from '@hedgedoc/html-to-react';

class HtmlComponent extends React.Component {
  render() {
    const html = '<div>Example HTML string</div>';
    return <div>{ ReactHtmlParser(html) }</div>;
  }
}


from ReactHtmlParser(html) to convertHtmlToReact (html, true);
